### PR TITLE
Update Seeds and Fix Statuses

### PR DESCRIPTION
**Pull request by emtalen**
### User Story
```
As a developer team
In order to fix our fuck ups
We need to go back and correct them
```
## Changes proposed in this pull request:
* Adding seeds with more users and some pings
* Removing all the hardcoded 422 statuses
* Removes the service until Thomas has time to help us with refactoring

## What I have learned working on this feature:
* We have learned that if you get a response from the API that is a 200 response and nothing else. If you try to change this and also send a message, the frontend will blow up or stop working when that handler is hit. Do not hard code statuses.

### CODE REVIEW

**Review by kfrostare — APPROVED** [review]
No comments /Kf

**Review by pgaunitz — APPROVED** [review]
LFSGTM

**Comment by johanbounce** [comment]
OMGGGG THIS IS GOOD

**Review by johanbounce — APPROVED** [review]
OMG SO APPROVED

**Pull request merged**
